using System;
using System.Collections.Generic;
using System.Text;

namespace SharpGasCore.Models
{
    /// <summary>
    /// GAS Response Model
    /// </summary>
    public class GasResponseDto
    {
        /// <summary>
        /// Gas autogenerated id
        /// </summary>
        public int GasId { get; set; }
        /// <summary>
        /// Gas mobile number (unique id for the microcontroller)
        /// </summary>
        public string GasMobileNumber { get; set; }
        /// <summary>
        /// Gas weight sent fro the contoller
        /// </summary>
        public double GasWeight { get; set; }
    }
}
